export const APP_VERSION = 'CAP CLAIR WEB13.29.1 - SUP AIP PARSER V3.1 FIABILISATION BETA';
export const APP_VERSION_SHORT = 'WEB13.29.1';
export const APP_TITLE = 'CAP CLAIR';
export const APP_SUBTITLE = 'Navigation VFR';
